steps:
  build-master:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/salt-master
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - latest
      - 3006.8
