version: '3.9'

services:
  master:
    container_name: salt-master
    image: coralhl/salt-master:latest
    restart: unless-stopped
    volumes:
      - "./roots:/home/salt/data/srv"
      - "./keys:/home/salt/data/keys"
      - "./logs:/home/salt/data/logs"
      - "./config/:/home/salt/data/config"
    ports:
      - "4505:4505"
      - "4506:4506"
      ### salt-api port
      - "8150:8000"
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      start_period: 30s
    environment:
      DEBUG: 'false'
      TZ: Europe/Moscow
      PUID: 1000
      PGID: 1000
      SALT_LOG_LEVEL: info
      ### salt-api settings
      SALT_API_ENABLED: 'True'
      SALT_API_USER: salt_api
      SALT_API_USER_PASS: 5uper-4wesome-Pass0rd
      ### salt-minion settings
      # SALT_MINION_ENABLED: 'True'
      # SALT_MINION_ID: builtin.minion

  salt-db:
    image: postgres:15-alpine
    container_name: salt-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=salt
      - POSTGRES_PASSWORD=salt
      - POSTGRES_DB=salt
    volumes:
      - "./db:/var/lib/postgresql/data"
